### ISSUE TITLE
Terminal on Bytes page is really hard to read/use

### ISSUE THREAD

**Issue by dulrich76** [Gage-Technologies/GigoApp#10]
![Screenshot_20240926-124219](https://github.com/user-attachments/assets/fceade8c-cef3-4b3e-8611-9dc874c01fc5)
hard to explain this one but I added a screenshot which may help. There is no clear border between the editor and terminal, this also causes the terminal to be slightly cut-off.

**Comment by mulr2023** [comment]
made terminal bigger for mobile and added a dividing line
