### ISSUE TITLE
No example units for JS, CPP, or C# in starting new Journeys

### ISSUE THREAD

**Issue by dulrich76** [Gage-Technologies/GigoApp#12]
If you try to start any of these journeys you get this error:

 LOG  Attempting to add unit: example_id_cpp
 ERROR  Error adding introductory unit to map: [Error: HTTP error! status: 500]

given that there is no intro unit this may be the problem

**Comment by mulr2023** [comment]
what journey's do you mean when you don't have a journey path at all yet?

**Comment by dulrich76** [comment]
There is no base journey for any of those languages. We have journeys for them but never made a base Journey for them.

**Comment by mulr2023** [comment]
removed options for languages that don't have starting units
