### ISSUE TITLE
Weird small "Add Unit" button that replaces large one when filtering by language

### ISSUE THREAD

**Issue by dulrich76** [Gage-Technologies/GigoApp#15]
![Screenshot_20240926-130338](https://github.com/user-attachments/assets/d0c6ddc2-211c-4747-bda4-b3906af24e25)
The lower right hand corner has this orange Add Unit button that replaces the larger one. Its inaccessible because of the bottom bar, and looks really bad.

**Comment by mulr2023** [comment]
how did you get this button?

**Comment by mulr2023** [comment]
give more detail on how you got this, i am not getting this

**Comment by dulrich76** [comment]
Like I said I swapped the language to something like only Golang, then went to the bottom of the page.

**Comment by mulr2023** [comment]
removed button, detour page made it unnecessary
