### ISSUE TITLE
Try a harder difficulty doesn't work

### ISSUE THREAD

**Issue by dulrich76** [Gage-Technologies/GigoApp#18]
After completing a Byte if you change the difficulty nothing seems to happen.

**Comment by mulr2023** [comment]
next time this happens will you do me a favor and try to change the difficulty twice? for some reason it seems like it works the second time but I want to confirm if that is happening regularly

**Comment by dulrich76** [comment]
yeah it seemed to work the second time. not sure why.

**Comment by mulr2023** [comment]
Increased button size that should fix this, closing for now and will reopen if it doesn't fix it once deployed
