### ISSUE TITLE
Error at account creation 

### ISSUE THREAD

**Issue by richardsonjacob1** [Gage-Technologies/GigoApp#21]
Entered account creation info - pressed submit - nothing happened - pressed submit again and the button changed, then reverted back to normal, then jumped me to this screen error message 

![Screenshot_20241009-154248](https://github.com/user-attachments/assets/09c585d5-a663-4cbb-a515-d7905be0d775)

**Comment by mulr2023** [comment]
this was on account creation? are you testing this on your phone from the app store download or are you testing it some other way? also how long was it after your last press of the button before it took you to this page?

**Comment by richardsonjacob1** [comment]
yes at account creation, this is directly from my phone - downloaded the app last friday
it was maybe a second after my last press before it jumped me here. probably 7-8 seconds from my first press

**Comment by mulr2023** [comment]
This should be fixed now. I build and the changes for this fix and the other and they should be available on the play store for you now. Update to check.
