### ISSUE TITLE
Journey Choose your Lane page Difficult to Read 

### ISSUE THREAD

**Issue by richardsonjacob1** [Gage-Technologies/GigoApp#22]
default white on white text very difficult to read

![Screenshot_20241009-154620](https://github.com/user-attachments/assets/fa91e623-cfc9-4bad-be8d-775347ece39b)

**Comment by mulr2023** [comment]
is your phone default light mode?

**Comment by richardsonjacob1** [comment]
yes

**Comment by mulr2023** [comment]
pushed on git but won't be visible until uploaded for you
