### ISSUE TITLE
Unaligned titles and icons 

### ISSUE THREAD

**Issue by richardsonjacob1** [Gage-Technologies/GigoApp#23]
At Journey start page - press Go Pro - press Learn More About Pro - titles and icons are unaligned and look (imo) sloppy. If there is difficulty aligning them perhaps just the Tier titles would look better 
The animation effects on this and the Go Pro page are sick tho 
![Screenshot 2024-10-09 155336](https://github.com/user-attachments/assets/32326c39-3f03-4bbb-b3a7-5033eeee5ae7)

**Comment by mulr2023** [comment]
![image](https://github.com/user-attachments/assets/15edaea1-3358-48bc-9bde-b533d51e373c)

decreased the space between and aligned them.
