### ISSUE TITLE
Clarify Tier availability per device

### ISSUE THREAD

**Issue by richardsonjacob1** [Gage-Technologies/GigoApp#24]
At Journey start page - press Go Pro - press Learn More About Pro - to me it is not clear at first pass that the basic tier is the only one available. Maybe we change the text to "available only on browser at gigo.dev" and move next to the tier title, maybe we should put a light grey out on the tiers here as well and overlay the text over top.
![Screenshot 2024-10-09 15533678](https://github.com/user-attachments/assets/008095c8-814d-4329-b3d4-c2e887ae69fe)

**Comment by mulr2023** [comment]
I changed the text but with the new text change, moving it to the top line causes the page to look super cluttered. Is there another place you would like it? I can put it below the title?
