### ISSUE TITLE
Redirect to gigo.dev on membership view

### ISSUE THREAD

**Issue by dulrich76** [Gage-Technologies/GigoApp#6]
Maybe when a user clicks on the different membership it redirects to the webpage. This would allow a user to upgrade their membership from the app and would generally just be nicer.

**Comment by mulr2023** [comment]
what does this mean? like when they click on the membership page?

**Comment by dulrich76** [comment]
when they click on the non basic memberships its just a popup. we should redirect to gigo.dev in a popout browser instead.

**Comment by mulr2023** [comment]
Keeping everything in app for now for this.
